#!/usr/bin/env bash
#
# Rails sを実行するためのラッパー
#

compose_run_option="--rm"
rails_env="development"
BACKEND_PORT="3000"
FRONTEND_PORT="8080"

docker-compose run ${compose_run_option} \
 -e RAILS_ENV=${rails_env}\
 backend bundle exec rails "$@"
